apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-backup
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-backup
            image: backup-img
            env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch-service-name"
            - name: BACKUP_DEST
              value: "/backup"
            volumeMounts:
            - name: data
              mountPath: /backup
          volumes:
          - name: data
            emptyDir: {}