apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: my-elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200

---

apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: my-kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601